### ISSUE TITLE
[#0306] Listar comentários de uma parceria

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-back#10]
## Descrição da atividade

- Criar rota para listagem de comentários de uma parceria (indepentente do tipo de comentário, pois todos serão listados da data mais recente para mais antiga). 

- Todo os usuário podem ver essa lista.

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente

## DoD

- [ ] Testado e integrado
- [x] Sem bugs observados / review
- [ ] Code review
- [ ] Atende aos critérios de aceite
- [x] Documentado
- [ ] Aceito pelo PO

**Comment by GabrielCamargoL** [comment]
# Documentação

## Descrição

Criar rota para listagem de comentários de uma parceria (indepentente do tipo de comentário, pois todos serão listados da data mais recente para mais antiga).

Todo os usuário podem ver essa lista.

## Tecnologias

NestJS, Prisma, PostgresSQL e Insomnia 

## Listar comentarios de um parceiro

**URL**: domain.api.com.br/partners/comment/:partnerId
**Method**: GET


- Controller 

```typescript

@Get('comment/:partnerId')
  async list(@Param('partnerId') partnerId: string) {
    return await this.partnerCommentService.listCommentsByPartner(partnerId);
  }

```

- Service

```typescript

 async listCommentsByPartner(id: string) {
    return await this.prismaService.partnerComment.findMany({
      where: {
        id: id
      },
      orderBy: {
        // createdAt: 'desc',
        updatedAt: 'desc'
      },
    })
  }

```
