### ISSUE TITLE
[#0308] Editar comentários de atualização de uma parceria

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-back#11]
## Descrição da atividade

Criar rota criada para edição de comentários de atualizações em parcerias.

## Informações para execução da atividade

Deve ser possível atualizar:
- Última atualização deve passar a ser a data da edição;
- O comentário em si.

Somente o dono do comentário pode realizar a edição, se ele ainda for administrador do sistema.

## DoR

- [x] Prototipado
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente

## DoD

- [ ] Testado e integrado
- [ ] Sem bugs observados / review
- [ ] Code review
- [ ] Atende aos critérios de aceite
- [x] Documentado
- [ ] Aceito pelo PO

**Comment by GabrielCamargoL** [comment]
# Documentação

## Descrição

Deve ser possível atualizar:
- Última atualização deve passar a ser a data da edição;
- O comentário em si.

Somente o dono do comentário pode realizar a edição, se ele ainda for administrador do sistema.

## Tecnologias

NestJS, Prisma, PostgresSQL e Insomnia 

## atualizar comentarios de um parceiro

**URL**: domain.api.com.br/partners/comment/:id
**Method**: GET


- Controller 

```typescript

@Put('comment/:id')
  async update(@Param('partnerId') partnerId: string, @Body() commentData: UpdateCommentDTO) {
    return await this.partnerCommentService.update(partnerId, commentData);
  }

```

- Service

```typescript

update(id: string, comment: UpdateCommentDTO) {
    return this.prismaService.partnerComment.update({
      data: comment,
      where: {
        id,
      },
    });
  }

```

---

## Autenticação JWT feita, porém, desativada devido ao escopo da sprint não suportá-lo

```typescript

@Controller('auth')
@ApiTags('Auth')
export class AuthController {
  constructor(private readonly authService: AuthService) { }

  @UseGuards(AuthGuard('local'))
  @Post('login')
  async login(@Req() req: any) {
    return await this.authService.login(req.user);
  }
}

```

```typescript
@Injectable()
export class AuthService {
  constructor(
    private readonly userService: UserService,
    private readonly jwtService: JwtService,
  ) { }

  async login(user) {
    user.password = undefined;
    const payload = { sub: user.id, email: user.email, role: user.role };


    return {
      user,
      token: this.jwtService.sign(payload),
    };
  }

  async validateUser(email: string, password: string) {
    let user;
    try {
      user = await this.userService.findUserByEmail(email);
    } catch (error) {
      return null;
    }

    const isPasswordValid = compareSync(password, user.password);
    if (!isPasswordValid) return null;

    return user;
  }
}
```

```typescript

@Injectable()
export class LocalStrategy extends PassportStrategy(Strategy) {
  constructor(private authService: AuthService) {
    super({ usernameField: 'email' })
  }

  async validate(email: string, password: string) {
    const user = await this.authService.validateUser(email, password);

    if (!user) throw new UnauthorizedException('E-mail e/ou são senha invalidos')

    return user;
  }

}

```

**Comment by gioliveirass** [comment]
@drisabelles ta aceito! assim que testar e integrar já pode fechar a task e passar pra done 🚀
