### ISSUE TITLE
[#0304] Adicionar comentários de atualização de uma parceria

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-back#12]
## Descrição da atividade

Criar rota para adicionar comentários de atualização em parceria.

## Informações para execução da atividade

Os comentários devem possuir as seguintes informações:
- Tipo de comentário (atualização/anotação);
- Última atualização (ordenar pela atualização mais recente);
- O comentário em si.

Somente o usuário administrador pode inserir comentários, mas todos no sistema podem ler.
Somente o dono do comentário pode editar o comentário.

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente

## DoD

- [ ] Testado e integrado
- [ ] Sem bugs observados / review
- [ ] Code review
- [ ] Atende aos critérios de aceite
- [x] Documentado
- [ ] Aceito pelo PO

**Comment by GabrielCamargoL** [comment]
# Documentação

## Descrição

Criar rota para adicionar comentários de atualização em parceria.

## Informações para execução da atividade

Os comentários devem possuir as seguintes informações:
- Tipo de comentário (atualização/anotação);
- Última atualização (ordenar pela atualização mais recente);
- O comentário em si.

Somente o usuário administrador pode inserir comentários, mas todos no sistema podem ler.
Somente o dono do comentário pode editar o comentário.

## Tecnologias

NestJS, Prisma, PostgresSQL e Insomnia 

## adicionar comentarios/notações sobre um parceiro

**URL**: domain.api.com.br/partners/comment
**Method**: POST


- Controller 

```typescript

@Post('comment')
  async addComment(@Body() commentData: CreateCommentDTO) {
    return await this.partnerCommentService.addComment(commentData);
  }

```

- Service

```typescript

  async addComment(comment: CreateCommentDTO) {
    return await this.prismaService.partnerComment.create({
      data: comment
    })
  }

```

- DTO

```typescript

export class CreateCommentDTO {

  @IsNotEmpty({ message: 'O id do parceiro(partnerID) precisa ser fornecido.' })
  @ApiProperty()
  partnerId: string

  @IsNotEmpty({ message: 'O id do usuário(userID) precisa ser fornecido' })
  @ApiProperty()
  userId: string

  @IsNotEmpty({ message: 'O id do usuário(userID) precisa ser fornecido' })
  @ApiProperty()
  comment: string

  @IsNotEmpty({ message: 'O tipo do comentário(commentType) deve ser fornecido.' })
  @IsEnum(CommentType, { message: "O tipo do comentario(commentType) deve ser 'ATUALIZACAO' ou 'ANOTACAO'." })
  @ApiProperty()
  commentType: CommentType
}
```

- Entidade no Banco de dados

```typescript

model PartnerComment {
  id String @id @default(uuid())

  Partner   Partner? @relation(fields: [partnerId], references: [id])
  partnerId String?
  User      User?    @relation(fields: [userId], references: [id])
  userId    String?

  comment     String
  commentType partnerCommentsType

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  @@map("partner_comments")
}

enum partnerCommentsType {
  ATUALIZACAO
  ANOTACAO
}



```

**Comment by drisabelles** [comment]
@gioliveirass

**Comment by gioliveirass** [comment]
@drisabelles ta aceito 🚀 assim que estiver testado e integrado pode passar pra done
