### ISSUE TITLE
[#0309] Excluir parcerias

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-back#13]
## Descrição da atividade

- Criar rota para excluir parcerias

## Informações para execução da atividade

- Somente usuários administradores podem excluir parcerias, e deve manter um histórico (deve ser possível identificar se a parceria foi excluída para que seja exbida corretamente no front e para que tenha suas ações limitidas a leitura)

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente

## DoD

- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

**Comment by ThHenrique** [comment]
Excluir/Desabilitar Parceria implementado.

- @gioliveirass Para implementar a questão de autorização, é necessário desenvolvermos o CRUD de usuário na primeira sprint.

**Comment by gioliveirass** [comment]
@ThHenrique a questão de autorização pode ser implementada no momento que o sistema passar a aceitar múltiplos usuários. Tudo bem?

**Comment by ThHenrique** [comment]
Tudo bem obrigado por responder

**Comment by gioliveirass** [comment]
tmj

**Comment by ThHenrique** [comment]
# Documentação

## Descrição

Para realizar a task mencionada acima foi adicionado ao controller do Partner a rota com o método DELETE que recebe o id da parceria como parâmetro e assim no service alteramos o campo "disabled" para True no BD. 

## Tecnologias

NestJS, Prisma, PostgresSQL e Insomnia 

## Disable Partner

**URL**: domain.api.com.br/partners/:id 
**Method**: DELETE


- Controller 

```typescript

@Delete('/:id')
  async disablePartner(@Param('id') id: string) {
    const partnerFound = await this.partnerService.findById(id);

    if (partnerFound === null) {
      throw new NotFoundException('Parceria não encontrada.');
    }

    await this.partnerService.disable(id);

    return { message: 'Parceria desativada com sucesso.' };
  }

```

Service

```typescript

disable(id: string) {
    return this.prismaService.partner.update({
      data: {
        disabled: true,
      },
      where: {
        id: id,
      },
    });
  }

```



Para mais detalhes, veja nas alterações realizadas :D
