### ISSUE TITLE
[#0602] Cadastro de reuniões

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-back#17]
## Descrição da atividade

Criar rota para cadastrar uma reunião com uma parceria.

## Informações para execução da atividade

- ~~Somente usuários administradores podem cadastrar uma reunião.~~
- As informações que devem ser armaazenadas são as seguintes: Parceria em questão (obrigatório), data (obrigatório), hora (obrigatório) e tema (opcional).

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente

## DoD

- [ ] Code review
- [ ] Testado e integrado
- [x] Documentado
- [ ] Aceito pelo PO

**Comment by GabrielCamargoL** [comment]
# Documentação

## Tecnologias
NestJS, Prisma, PostgresSQL, Insomnia, VSCODE, beekeeper Studio portable

### Criação da Reunião

|       Requisição       |      Retorno      |
|:-----------------:|:----------------:|
| ![image](https://user-images.githubusercontent.com/55204419/231311297-23996f1b-9a66-40f7-9898-7f6b0defafe6.png) | ![image](https://user-images.githubusercontent.com/55204419/231311311-5213107d-8471-44c1-b711-f27cb20e686c.png) |

---
**URL**: domain.api.com.br/meetings 
**Method**: POST

- Controller 

```typescript
@Post()
  @UseGuards(AuthGuard('jwt'))
  async createPartner(@Body() meetingData: CreateMeetingDTO) {
    return this.meetingService.create(meetingData);
  }
```

- Service

```typescript
async create(meeting: CreateMeetingDTO) {
  return this.prismaService.meeting.create({
    data: meeting,
  });
}
```

- DTO
```typescript
export class CreateMeetingDTO {
	@IsNotEmpty({ message: 'O título(title) da reunião precisa ser informado' })
	@ApiProperty()
	title: string;

	@IsNotEmpty({ message: 'O id da parceria(partnerId) da reunião precisa ser informado' })
	@IsUUID(undefined, { message: 'A estrutura do id da parceria(partnerId) precisa ser de UUID' })
	@ApiProperty()
	partnerId: string;

	@IsNotEmpty({ message: 'A descrição(description) da reunião precisa ser informada' })
	@ApiProperty()
	description: string;

	@IsNotEmpty({ message: 'A data e hora(meetingDateTime) da reunião precisa ser informada' })
	@IsDateString()
	meetingDateTime: Date
}
```

**Comment by gioliveirass** [comment]
@GabrielCamargoL @drisabelles show
