### ISSUE TITLE
[#0604] Atualização de reuniões

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-back#18]
## Descrição da atividade

Criar rota para atualização de reuniões.

## Informações para execução da atividade

- ~~Somente usuários administradores podem atualizar uma reunião.~~
- Todas as informações inseridas no cadastro podem ser atualizadas, menos o nome da parceria (que só pode ser lido).

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente

## DoD

- [ ] Code review
- [ ] Testado e integrado
- [x] Documentado
- [ ] Aceito pelo PO

**Comment by GabrielCamargoL** [comment]
# Documentação

## Tecnologias
NestJS, Prisma, PostgresSQL, Insomnia, VSCODE, beekeeper Studio portable

### Atualização da Reunião

|       Antes       |      Depois      |
|:-----------------:|:----------------:|
| ![image](https://user-images.githubusercontent.com/55204419/231313659-56bf52d9-3649-4e78-88e2-ad238e68cb3c.png) | ![image](https://user-images.githubusercontent.com/55204419/231314144-7de41470-5a5b-4417-a575-e84aaac97b69.png) |

---
**URL**: domain.api.com.br/meetings/:id
**Method**: PUT

- Controller 

```typescript
	@Put('/:id')
	@UseGuards(AuthGuard('jwt'))
	async updateMeeting(@Param('id') id: string, @Body() dataToUpdate: UpdateMeetingDTO) {
		const meetingFound = await this.meetingService.findById(id);

		if (meetingFound === null) throw new NotFoundException('Reunião não encontrada.');

		const meetingUpdated = await this.meetingService.update(id, dataToUpdate);
		return {
			meeting: meetingUpdated,
			message: 'Dados da Reunião Atualizado com sucesso.',
		};
	}
```

- Service

```typescript
update(id: string, meeting: UpdateMeetingDTO) {
		return this.prismaService.meeting.update({
			data: meeting,
			where: {
				id,
			},
		});
	}
```

- DTO
```typescript
export class UpdateMeetingDTO {
	@IsNotEmpty({ message: 'O título(title) da reunião precisa ser informado' })
	@ApiProperty()
	title: string;

	@IsOptional()
	@ApiProperty()
	description: string;

	@IsNotEmpty({ message: 'A data e hora(meetingDateTime) da reunião precisa ser informada' })
	@IsDateString()
	meetingDateTime: Date;
}
```

**Comment by gioliveirass** [comment]
@drisabelles @GabrielCamargoL show
