### ISSUE TITLE
[#0606] Listagem de reuniões na homepage

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-back#19]
## Descrição da atividade

Criar rota para listagem de todas as reuniões.

## Informações para execução da atividade

- Qualquer usuário pode ver a lista de reuniões.
- Deve ser separado entre reuniões futuras e reuniões passadas.
- Deve ter um botão de ver mais para exibir mais reuniões.

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente

## DoD

- [ ] Code review
- [ ] Testado e integrado
- [ ] Documentado
- [ ] Aceito pelo PO

**Comment by drisabelles** [comment]
@gioliveirass temos duas listagens de reuniões segundo o protótipo, as que as próximas e as últimas que aconteceram. Vamos manter ambas as listagens na mesma task ou serão tasks separadas?

**Comment by gioliveirass** [comment]
@drisabelles podemos manter na mesma task e adicionar os dois tipos de listagem como critério de aceite, o que acha?

**Comment by gioliveirass** [comment]
@GabrielCamargoL @drisabelles aprovadooooo
