### ISSUE TITLE
[#0703] Edição de anotações em reuniões

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-back#23]
## Descrição da atividade

Criar rota para edição de anotações em reuniões.

## Informações para execução da atividade

- Somente o usuário que criou o comentário pode editar uma anotação, ~~se ele ainda for administrador~~

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente

## DoD

- [x] Code review
- [x] Testado e integrado
- [x] Documentado
- [x] Aceito pelo PO

**Comment by ThHenrique** [comment]
# Documentação

## Tecnologias
NestJS, Prisma, PostgresSQL, Insomnia, VSCODE, beekeeper Studio portable

## Descrição
CRUD de anotações das reuniões.

## Issues Relacionada
#22 #23 #24 

## Lista de Mudanças

- Criação de comentário da reunião;
- Listagens dos comentários das reuniões;
- Atualização do comentário da Reunião;
- Exclusão do comentário da Reunião;

## Rotas
para visualizar as rotas, utilize o swagger e veja a aba "Meetings" em (http://localhost:3000/api)[localhost:3000/api].

---

## Comentários Adicionais

A atualização do comentário da reunião só poderá ser feita pelo usuário que realizou a ação

```typescript 
async update(@Param('commentId') commentId: string, @Body() commentData: UpdateMeetingCommentDTO, @Request() req) {
		const user: User = req.user;

		const meetingCommentFound = await this.meetingCommentService.findById(commentId);

		if (meetingCommentFound === null) {
			throw new NotFoundException('Comentário da reunião não encontrado');
		} else if (meetingCommentFound.User.id !== user.id) {
			throw new UnauthorizedException('Somente o usuário que criou o comentário pode editá-la.');
		}

		const meetingCommentUpdated = await this.meetingCommentService.update(commentId, commentData);

		return {
			meetingComment: meetingCommentUpdated,
			message: 'Comentário da reunião Atualizado com sucesso.',
		};
	}
```

## Checklist
- [x] O código foi testado e está funcionando corretamente
- [x] As mudanças foram revisadas por um colega de equipe
- [ ] A documentação foi atualizada, se necessário
- [ ] A issue relacionada foi atualizada, se existir
