### ISSUE TITLE
[#0402] Cadastro de usuário

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-back#25]
## Descrição da atividade

Criar rota para cadastro de usuários.

## Informações necessárias para execução da atividade.

- Dados do usuário: Nome, e-mail, senha e nível de privilégio (por padrão será simples e poderá ser atualizado posteriormente por um administrador). Todas as informações são obrigatórias.

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente

## DoD

- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

**Comment by GabrielCamargoL** [comment]
## Resultados Obtidos
![image](https://user-images.githubusercontent.com/55204419/227392883-c16a17b6-7847-45da-9871-ea62c2136a45.png)

## Códigos

```typescript
  async create(user: CreateUserDTO) {
    const saltOrRounds = 10;
    const hash = await bcrypt.hash(user.password, saltOrRounds);
    user.password = hash;

    return this.prismaService.user.create({
      data: user,
    });
  }

```

**Comment by gioliveirass** [comment]
@drisabelles vou validar com o cliente as mudanças antes de dar o OK, tudo bem?
