### ISSUE TITLE
[#0403] Listagem de usuário

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-back#26]
## Descrição da atividade

Criar rota para listagem de usuários.

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente

## DoD

- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

**Comment by GabrielCamargoL** [comment]
## Resultado Obtidos
![image](https://user-images.githubusercontent.com/55204419/227393607-44d9a0fb-9434-417b-becb-10d8679db0e1.png)

## Códigos


```typescript

@Get()
	// @UseGuards(AuthGuard('jwt'))
	async index() {
		const users = this.userService.findAll();
		return users;
	}

```

**Comment by gioliveirass** [comment]
@drisabelles vou validar com o cliente as mudanças antes de dar o OK, tudo bem?
