### ISSUE TITLE
[#0404] Excluir usuário

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-back#27]
## Descrição da atividade

Criar rota para exclusão de usuários.

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente

## DoD

- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

**Comment by GabrielCamargoL** [comment]
## Resultados Obtidos
![image](https://user-images.githubusercontent.com/55204419/227391139-3b6ceca5-b376-45a5-9f16-163e78a67365.png)

## Códigos

```typescript

@Delete('/:id')
  // @UseGuards(AuthGuard('jwt'))
  async deleteUser(@Param('id') id: string) {
    const userFound = await this.userService.findById(id);
    if (userFound === null) throw new NotFoundException('Usuário não encontrado.')

    return { message: 'Usuário removido com sucesso.' }
  }

```

**Comment by gioliveirass** [comment]
@drisabelles vou validar com o cliente as mudanças antes de dar o OK, tudo bem?
