### ISSUE TITLE
[#0501] Autenticação do usuário

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-back#28]
## Descrição da atividade

Criar rota para autenticação de usuários.

## Informações necessárias para execução da atividade.

- O usuário simples pode realizar as seguintes ações:
• Vizualizar a dashboard;
• Somente vizualizar as reuniões e suas anotações;
• Somente vizualizar informações de parcerias (incluindo comentários);
• Se cadastrar no sistema, uma vez que a aplicação é de utilização interna da empresa.

- O usuário administrador pode realizar as seguintes ações:
• Vizualizar a dashboard;
• Cadastrar, editar e excluir reuniões;
• Cadastrar, editar e excluir parcerias;
• Adicionar comentários em parcerias;
• Adicionar anotações em reuniões;
• Deletar usuários;
• Promover um usuário a administrador.

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente

## DoD

- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

**Comment by GabrielCamargoL** [comment]
## Resultados obtidos

![image](https://user-images.githubusercontent.com/55204419/227388405-cb785206-54fd-44ac-bc42-a1c1bf99300d.png)

## Códigos

```typescript

@Injectable()
export class AuthService {
  constructor(
    private readonly userService: UserService,
    private readonly jwtService: JwtService,
  ) { }

  async login(user) {
    user.password = undefined;
    const payload = { sub: user.id, email: user.email, role: user.role };


    return {
      user,
      token: this.jwtService.sign(payload),
    };
  }

  async validateUser(email: string, password: string) {
    let user;
    try {
      user = await this.userService.findUserByEmail(email);
    } catch (error) {
      return null;
    }

    const isPasswordValid = compareSync(password, user.password);
    if (!isPasswordValid) return null;

    return user;
  }
}

```


```typescript
@Injectable()
export class JwtStrategy extends PassportStrategy(Strategy) {
  constructor() {
    super({
      jwtFromRequest: ExtractJwt.fromAuthHeaderAsBearerToken(),
      ignoreExpiration: false,
      secretOrKey: process.env.JWT_SECRET_KEY
    })
  }

  validate(payload: any) {
    return { id: payload.sub, email: payload.email, role: payload.role }
  }
}

```

**Comment by GabrielCamargoL** [comment]
@gioliveirass Eu apenas fiz a autenticação, ignorando a role do usuario, com o objetivo de saber quem está requisitando para ligá-lo aos relacionamentos das entidades através dos ID's e tambem por estar na primeira sprint.

Gostaria da sua opinião quanto a isso, caso queira a "autorização" por privilégios.
Deixarei a issue em aberto aguardando sua resposta.

**Comment by gioliveirass** [comment]
@GabrielCamargoL Se tiver a autorização por privilégios, teríamos que retomar essa task futuramente? Se sim, seria interessante tentar encerrar isso já nessa sprint, mas precisaria ver com a master se temos tempo para isso. 

Podemos aproveitar para decidir isso hoje pois o cliente ainda não me respondeu da última dúvida.
