### ISSUE TITLE
[#0005] Setup Swagger

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-back#29]
## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)

## DoD

- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

**Comment by GabrielCamargoL** [comment]
## [Swagger](https://owlpartners.onrender.com/api#/owlPartners)
![image](https://user-images.githubusercontent.com/55204419/227387699-11c396af-b166-4caa-9861-5ef571c85b74.png)


-> main.ts
```typescript

const config = new DocumentBuilder()
		.setTitle('OwlPartners')
		.setDescription('OwlPartners Service')
		.setVersion('1.0')
		.addTag('owlPartners')
		.build();
	const document = SwaggerModule.createDocument(app, config);
	SwaggerModule.setup('api', app, document);
```
