### ISSUE TITLE
[#0004] Deploy backend

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-back#30]
## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)

## DoD

- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

**Comment by gioliveirass** [comment]
@GabrielCamargoL se precisar de alguma informação para essa task me avisa por favor 👍

**Comment by GabrielCamargoL** [comment]
## Deploy feito no Render

[https://owlpartners.onrender.com/users](https://owlpartners.onrender.com/users)

![image](https://user-images.githubusercontent.com/55204419/227387357-7fa5d7b2-6db2-4f8c-8f30-f75cce81dfb2.png)

![image](https://user-images.githubusercontent.com/55204419/227387446-0027226b-a45b-461e-aee3-7563951e42e2.png)
