### ISSUE TITLE
[#0613] Listagem de reuniões na tela de detalhes da parceria

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/owl-partners-back#33]
## 📄 Descrição da atividade

Na aba "Reuniões" da tela de parcerias deve ser exibida a listagem de reuniões da parceria ordenada pela data mais recente para mais antiga.

## 🛠 Protótipo

![Image](https://user-images.githubusercontent.com/78885451/230447272-7f946306-5b30-4788-b67a-4ea1a7cf1906.png)

### DoR: Definition of Ready

- [x] **Cabe em uma sprint:** De preferência, não deve ser maior que 8 story points
- [x] **Prototipado:** O protótipo já está disponível no [Figma](https://www.figma.com/file/OfE7DUkKkBgC7O3fmDoulH/Owl-Partners-(Oracle)?node-id=11-195&t=txTFGhY0EvM3VWcn-0)
- [x] **Validado com o cliente:** As informações da atividade foram validadas pelo cliente

### Critérios de aceite

- [ ] Deve listar todas as reuniões da parceria em específico
- [ ] Deve ordenar da data mais recente para mais antiga
- [ ] Ao clicar em um reunião, deve abrir a página de detalhes dela
- [ ] Deve estar divididas entre "reuniões passadas" e "reuniões futuras"

### DoD: Definition of Done

- [ ] **Atende aos critérios de aceite:** Todos os critérios de aceite definidos para a atividade foram cumpridos
- [ ] **Code review:** O code review foi realizado e, se identificada a necessidade, as correções foram realizadas
- [ ] **Testado e integrado:** A feature desenvolvida já se encontra na branch Development e funciona em harmonia com as demais funcionalidades (navegação em funcionamento, não gerou bugs, conflitos foram resolvidos)
- [ ] **Documentado:** A feature desenvolvida foi documentada pelo desenvolvedor
- [ ] **Aceito pelo PO:** A feture desenvolvida foi aprovada pelo PO

**Comment by gioliveirass** [comment]
@GabrielCamargoL protótipo atualizado de acordo com o que conversamos na sexta dia 04/04

**Comment by GabrielCamargoL** [comment]
# Documentação

## Tecnologias
NestJS, Prisma, PostgresSQL, Insomnia, VSCODE, beekeeper Studio portable

### Listagem de Reuniões

![image](https://user-images.githubusercontent.com/55204419/231313401-f63b7c52-3771-4d28-bb3f-ef8e7ff42cd1.png)

---
**URL**: domain.api.com.br/meetings
**URL**: domain.api.com.br/meetings/partner/:id
**Method**: GET

- Controller 

```typescript
@Get()
	@UseGuards(AuthGuard('jwt'))
	async meetings() {
		return this.meetingService.findAll();
	}

	@Get('partner/:partnerId')
	@UseGuards(AuthGuard('jwt'))
	async meetingsByPartner(@Param('partnerId') partnerId: string) {
		return this.meetingService.findByPartnerId(partnerId);
	}
```

- Service

```typescript
	async findAll() {
		const upcomingMeetings = await this.prismaService.meeting.findMany({
			select: {
				id: true,
				title: true,
				description: true,
				meetingDateTime: true,
				Partner: {
					select: {
						id: true,
						name: true,
					}
				}
			},
			where: {
				meetingDateTime: {
					gt: getCurrentBrDateTimeISO()
				}
			},
			orderBy: { meetingDateTime: 'asc' }
		});

		const pastMeetings = await this.prismaService.meeting.findMany({
			select: {
				id: true,
				title: true,
				description: true,
				meetingDateTime: true,
				Partner: {
					select: {
						id: true,
						name: true,
					}
				}
			},
			where: {
				meetingDateTime: {
					lt: getCurrentBrDateTimeISO()
				}
			},
			orderBy: { meetingDateTime: 'asc' }
		});

		return { upcomingMeetings, pastMeetings }
	}

```


função de comparação de datas para separação entre reuniões futuras e passadas:
```typescript
export function getCurrentBrDateTimeISO(): string {
	const now = new Date()
	const offset = -180 // offset em minutos (-180 equivale a -3 horas, ou seja, horário de Brasília)
	const localTimestamp = now.getTime() + offset * 60 * 1000 // adiciona o offset em milissegundos

	const localDate = new Date(localTimestamp)
	const formattedDate = localDate.toISOString()

	console.log(formattedDate);

	return formattedDate
}
```

**Comment by gioliveirass** [comment]
@GabrielCamargoL @drisabelles showww
