### ISSUE TITLE
[#0114] Remover validação de existência de e-mail repetido ao cadastrar parcerias

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-back#34]
## 📄 Descrição da atividade

Atualmente, ocorre uma validação que não permite cadastrar mais de uma parceria com o mesmo e-mail de contato. No entanto, o correto é que cada parceria tenha a opção de cadastrar ou não um único e-mail de contato, independente de qual seja esse e-mail. Portanto, o objetivo dessa atividade é permitir que mais de uma parceria tenha o mesmo e-mail de contato cadastrado. 

### DoR: Definition of Ready

- [x] **Cabe em uma sprint:** De preferência, não deve ser maior que 8 story points

### Critérios de aceite

- [x] Alterar back-end para permitir mais que mais de uma parceria possua o mesmo e-mail de contato

### DoD: Definition of Done

- [x] **Atende aos critérios de aceite:** Todos os critérios de aceite definidos para a atividade foram cumpridos
- [ ] **Code review:** O code review foi realizado e, se identificada a necessidade, as correções foram realizadas
- [ ] **Testado e integrado:** A feature desenvolvida já se encontra na branch Development e funciona em harmonia com as demais funcionalidades (navegação em funcionamento, não gerou bugs, conflitos foram resolvidos)
- [x] **Documentado:** A feature desenvolvida foi documentada pelo desenvolvedor
- [ ] **Aceito pelo PO:** A feture desenvolvida foi aprovada pelo PO

**Comment by GabrielCamargoL** [comment]
retirando o email unico dos parceiros com SQL

```sql
-- DropIndex
DROP INDEX "partners_email_key";
```

**Comment by gioliveirass** [comment]
@GabrielCamargoL @drisabelles showw
