### ISSUE TITLE
[#0103] Cadastrar parceria

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-back#4]
## Descrição da atividade

Criar uma rota que deverá ser consumida pelo front-end para realizar a criação de uma parceria.

## Informações para execução da atividade

As seguintes informações devem ser armazenadas;
- Nome;
- E-mail;
- Telefone;
- Endereço;
- Classificação (colégios, universidades, secretarias e governos);
- Número de membros;
- Localização;
- Status*.

*Os status podem ser os seguintes: 
- Em prospecção;
- Primeiro contato feito;
- Primeira reunião marcada/realizada;
- Documentação enviada/em análise (Parceiro);
- Documentação devolvida (Em análise Academy);
- Documentação devolvida (Em análise Legal);
- Documentação Analisada devolvida (Parceiro)
- Em preparação de Executive Sumary (Academy);
- ES em analise (Legal), ES em analise (Academy Global);
- Pronto para assinatura, Parceria Firmada.

## DoR

- [x] Validado com cliente
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)

## DoD

- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

**Comment by gioliveirass** [comment]
@ThHenrique o email, telefone e o CEP são obrigatórios?

**Comment by ThHenrique** [comment]
O email e o CEP da parceria são campos opcionais. Os campos obrigatórios são **name** e **status**
