### ISSUE TITLE
[#0202] Fornecer dados para o dashboard

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/owl-partners-back#40]
## 📄 Descrição da atividade

Deve fornecer as seguintes informações a serem exibidas no dashboard:
- Número total de parcerias em desenvolvimento;
- TOP 10 parcerias em desenvolvimento com maior quantidade de membros (vizualição em forma de gráfico de barras);
- Parcerias em desenvolvimento por status (vizualição em forma de gráfico de barras);
- Parcerias em desenvolvimento por estado (vizualição em forma de gráfico de barras);
- Parcerias em desenvolvimento por classificação (vizualição em forma de gráfico de barras);
- Próxima reunião agendada com parceria em desenvolvimento.

Obs.: "Parceria em desenvolvimento" é como o cliente passou a chamar as "Parcerias ativas".

## 🛠 Protótipo

![Image](https://user-images.githubusercontent.com/78885451/234132917-54b9c848-50d2-419f-985f-b9a64fa6b224.png)

### DoR: Definition of Ready

- [x] **Cabe em uma sprint:** De preferência, não deve ser maior que 8 story points
- [x] **Prototipado:** O protótipo já está disponível no [Figma](https://www.figma.com/file/OfE7DUkKkBgC7O3fmDoulH/Owl-Partners-(Oracle)?node-id=11-195&t=txTFGhY0EvM3VWcn-0)
- [ ] **Validado com o cliente:** As informações da atividade foram validadas pelo cliente

### Critérios de aceite

- [x] Deve fornecer número total de parcerias em desenvolvimento.
- [x] Deve fornecer TOP 10 parcerias em desenvolvimento com maior quantidade de membros (vizualição em forma de gráfico de barras).
- [x] Deve fornecer parcerias em desenvolvimento por status (vizualição em forma de gráfico de barras).
- [x] Deve fornecer parcerias em desenvolvimento por estado (vizualição em forma de gráfico de barras).
- [x] Deve fornecer parcerias em desenvolvimento por classificação (vizualição em forma de gráfico de barras).
- [x] Deve fornecer próxima reunião agendada com parceria em desenvolvimento.

### DoD: Definition of Done

- [ ] **Atende aos critérios de aceite:** Todos os critérios de aceite definidos para a atividade foram cumpridos
- [ ] **Code review:** O code review foi realizado e, se identificada a necessidade, as correções foram realizadas
- [ ] **Testado e integrado:** A feature desenvolvida já se encontra na branch Development e funciona em harmonia com as demais funcionalidades (navegação em funcionamento, não gerou bugs, conflitos foram resolvidos)
- [x] **Documentado:** A feature desenvolvida foi documentada pelo desenvolvedor
- [ ] **Aceito pelo PO:** A feture desenvolvida foi aprovada pelo PO

**Comment by GabrielCamargoL** [comment]
@gioliveirass @drisabelles os itens: 

- Parcerias em desenvolvimento por status (vizualição em forma de gráfico de barras);
- Parcerias em desenvolvimento por estado (vizualição em forma de gráfico de barras);
- Parcerias em desenvolvimento por classificação (vizualição em forma de gráfico de barras);

terei que entregar quais são as parcerias ou somente os numeros de cada item? pensando no cenário em que estão cadastrados 20 parcerias em um status (ex: em prospecção). Como ficaria a visualização disso em um grafico de barras? 

O que eu consigo entregar no momento sem essa visualização são somente os números, como na print a seguir: 

![image](https://user-images.githubusercontent.com/55204419/235302828-89ecbb68-bbc5-404d-90c9-4e397bb97ece.png)

**Comment by GabrielCamargoL** [comment]
# Documentação

## Tecnologias
NestJS, Prisma, PostgresSQL, Insomnia, VSCODE, beekeeper Studio portable

## DASHBOARD
As prints são da mesma chamada, cortei para organizar melhor a vizualização

### Total de parcerias ativas e top 10 parcerias com mais membros
![image](https://user-images.githubusercontent.com/55204419/235302563-53b426a8-922d-497f-96ee-8ff04e015d78.png)

### GroupBy das parcerias ativas por: status, estado e classificação
![image](https://user-images.githubusercontent.com/55204419/235302576-0a7ccebb-606f-4069-8622-9c66c55e5277.png)

### Reunião mais proxima e o respectivo parceiro envolvido
![image](https://user-images.githubusercontent.com/55204419/235302590-9ebd1a7a-dba2-4b8f-b56f-24b46637ac94.png)


---
**URL**: domain.api.com.br/dashboard
**Method**: GET

- Controller 
```typescript
@Get()
  @UseGuards(AuthGuard('jwt'))
    async index() {
      return await this.dashboardService.dashboard();
    }
```

- Service
```typescript
@Injectable()
export class DashboardService {
	constructor(private readonly prismaService: PrismaService) { }

	async dashboard() {
		const totalActivePartners = await this.prismaService.partner.count({
			where: { disabled: false }
		});


		const partnersPerStatus = await this.prismaService.partner.groupBy({
			by: ['status'],
			where: { disabled: false },
			_count: true,
			orderBy: {
				status: 'asc'
			}
		});

		const partnersPerState = await this.prismaService.partner.groupBy({
			by: ['state'],
			where: { disabled: false },
			_count: true,
			orderBy: {
				_count: {
					state: 'desc'
				}
			}
		});

		const partnerPerClassification = await this.prismaService.partner.groupBy({
			by: ['classification'],
			where: { disabled: false },
			_count: true
		});

		const top10MostMembers = await this.prismaService.partner.findMany({
			where: { disabled: false },
			orderBy: { memberNumber: 'desc', },
			take: 10
		});

		const nextMeeting = await this.prismaService.meeting.findFirst({
			where: {
				meetingDateTime: { gt: getCurrentBrDateTimeISO() },
				Partner: { disabled: false }
			},
			include: {
				Partner: true
			},
			orderBy: { meetingDateTime: 'asc' }
		});

		return {
			totalActivePartners,
			top10MostMembers,

			partnersPerStatus,
			partnersPerState,
			partnerPerClassification,

			nextMeeting
		}
	}
}
```

**Comment by drisabelles** [comment]
@GabrielCamargoL @gioliveirass referente a esses gráficos:

- Parcerias em desenvolvimento por status (vizualição em forma de gráfico de barras);
- Parcerias em desenvolvimento por estado (vizualição em forma de gráfico de barras);
- Parcerias em desenvolvimento por classificação (vizualição em forma de gráfico de barras);

Seriam entregues somente os números de quantas parcerias há por status/estado/classificação, ex.: 20 em sp, 12 em am

**Comment by gioliveirass** [comment]
sim, seria um gráfico de barras para apresentar o total de parcerias por categoria.

**Comment by gioliveirass** [comment]
@drisabelles essa atividade está prevista para próxima sprint.

**Comment by drisabelles** [comment]
@gioliveirass agora a partir dela seria só implementar os dados fornecidos para o dashboard na prox sprint
