### ISSUE TITLE
[#0101] Modelagem da tabela Parceria

### ISSUE THREAD

**Issue by ThHenrique** [The-Bugger-Ducks/owl-partners-back#6]

**Comment by drisabelles** [comment]
Considerações da modelagem: 

- informações validadas ontem pela p.o: só o dono do comentário altera e só salva a data da última atualização
- informações validadas hoje pela p.o: a ordenação dos comentários será feita pela data de edição dele

**Comment by ThHenrique** [comment]
Adicionei a modelagem o campo "disabled" como boolean default false. Utilizado para demonstrar que uma parceria foi excluida

@GabrielCamargoL

**Comment by GabrielCamargoL** [comment]
![Image](https://user-images.githubusercontent.com/55204419/226508100-d33e8195-00d3-45c9-9751-03a4232c5ce1.png)
