### ISSUE TITLE
[#0401] Modelagem da tabela Usuário

### ISSUE THREAD

**Issue by ThHenrique** [The-Bugger-Ducks/owl-partners-back#7]

**Comment by drisabelles** [comment]
Considerações sobre a modelagem: 

- o admin também pode rebaixar um outro admin para usuário simples
- dados de usuário validados hoje pela p.o:  Nome, e-mail, senha e nível de privilégio (por padrão será simples e poderá ser atualizado posteriormente por um administrador).

**Comment by GabrielCamargoL** [comment]
![Image](https://user-images.githubusercontent.com/55204419/226507895-8efb72e5-69de-41be-8d05-77d11d7aceba.png)


```typescript

model User {
  id        String   @id @default(uuid())
  name      String?
  lastName  String?
  email     String   @unique
  password  String
  createdAt DateTime @default(now())
  role      UserRole @default(SIMPLE)

  comments PartnerComment[]

  @@map("users")
}

enum UserRole {
  ADMIN
  SIMPLE
}

```
