### ISSUE TITLE
[#0501] Modelagem da tabela Reunião

### ISSUE THREAD

**Issue by ThHenrique** [The-Bugger-Ducks/owl-partners-back#8]

**Comment by drisabelles** [comment]
Considerações sobre a modelagem: 

- informações de cadastro de reunião validadas hoje pela p.o: parceria em questão, data, hora e tema (opcional).

**Comment by GabrielCamargoL** [comment]
![Image](https://user-images.githubusercontent.com/55204419/226508033-b0202902-7abf-4617-a9bd-7c54eaab72e7.png)
