### ISSUE TITLE
[#0105] Listar parceria

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-back#9]
## Descrição da atividade

Criar rota que deverá ser consumida pelo front para listagem de parcerias. Deverá ser possível buscar pelo nome da parceria e filtrá-las por parcerias ativas e parcerias desativadas.

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente

## DoD

- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

**Comment by ThHenrique** [comment]
# Documentação

## Descrição

Para realizar a task mencionada acima foi adicionado ao controller do Partner a rota com o método GET que recebe o nome da parceria como parâmetro e assim no service filtramos as parcerias com o nome informado

## Tecnologias

NestJS, Prisma, PostgresSQL e Insomnia 

## Disable Partner

**URL**: domain.api.com.br/partners/search/:name 
**Method**: GET


- Controller 

```typescript

@Get('/search/:name')
  async partnersByName(@Param('name') name: string) {
    return this.partnerService.findByName(name);
  }

```

- Service

```typescript

async findByName(name: string) {
    return this.prismaService.partner.findMany({
      where: {
        name: { contains: name, mode: 'insensitive' },
      },
      orderBy: {
        createdAt: 'desc',
      },
    });
  }

```



Para mais detalhes, veja nas alterações realizadas :D

**Comment by gioliveirass** [comment]
@ThHenrique é possível listar apenas parcerias "deletadas" e apenas parcerias "ativas"? Para ficar conforme protótipo:

![Image](https://user-images.githubusercontent.com/78885451/226426314-20643e01-311c-4b7c-a9b2-f4d452d3de7a.png)

**Comment by ThHenrique** [comment]
Sim, vou atualizar a descrição da Task e realizar essa implementação. Vou me basear nos filtros aplicados nos nossos projetos anteriores

**Comment by ThHenrique** [comment]
@gioliveirass acc ai 👻
